version: "3.9"

services:

  caddy:
    image: "docker.io/caddy:2"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:8443:8443/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "caddy-data:/data/"

  biserver:
    image: "repo.stratebi.com/lincebi/biserver:8.3"
    networks:
      - "biserver"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "../lincebi-bundle/build/lincebi.zip:/etc/biserver.init.d/10_lincebi.zip:ro"
      - "./biserver.init.d/30_language-pack-es.sh:/etc/biserver.init.d/30_language-pack-es.sh:ro"
      - "./biserver.init.d/30_stsearch.sh:/etc/biserver.init.d/30_stsearch.sh:ro"
      - "./biserver.init.d/90_configuration/:/etc/biserver.init.d/90_configuration/:ro"
    environment:
      IS_PROXIED: "true"
      PROXY_SCHEME: "https"
      PROXY_PORT: "8443"
      FQSU_PROTOCOL: "https"
      FQSU_DOMAIN: "localhost"
      FQSU_PORT: "8443"
      DEFAULT_ADMIN_PASSWORD: "password"
      STORAGE_TYPE: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      STAGILE_LICENSE_B64: "${STAGILE_LICENSE_B64-}"
      STDASHBOARD_LICENSE_B64: "${STDASHBOARD_LICENSE_B64-}"
      STMETADATAWIZARD_LICENSE_B64: "${STMETADATAWIZARD_LICENSE_B64-}"
      STPANELS_LICENSE_B64: "${STPANELS_LICENSE_B64-}"
      STPIVOT_LICENSE_B64: "${STPIVOT_LICENSE_B64-}"
      STREPORT_LICENSE_B64: "${STREPORT_LICENSE_B64-}"
      POWERBI_DEFAULT_CLIENT_ID: "${POWERBI_DEFAULT_CLIENT_ID-}"
      POWERBI_DEFAULT_AUTHENTICATION_TYPE: "ServicePrincipal"
      POWERBI_DEFAULT_SERVICEPRINCIPAL_TENANT_ID: "${POWERBI_DEFAULT_SERVICEPRINCIPAL_TENANT_ID-}"
      POWERBI_DEFAULT_SERVICEPRINCIPAL_CLIENT_SECRET: "${POWERBI_DEFAULT_SERVICEPRINCIPAL_CLIENT_SECRET-}"
    depends_on:
      - "postgres"

  postgres:
    image: "docker.io/postgres:14"
    networks:
      - "biserver"
    ports:
      - "127.0.0.1:5432:5432/tcp"
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"

networks:

  biserver:
    driver: "bridge"
    internal: false

volumes:

  caddy-data:
  postgres-data:
